language: node_js
node_js:
- '8'
cache: yarn
before_install:
- openssl aes-256-cbc -K $encrypted_c537c6d0a92e_key -iv $encrypted_c537c6d0a92e_iv
  -in .travis.enc -out publishConfig.js -d
script:
- yarn pub
branches:
  only:
  - master
